version: "3"

tasks:
  default:
    desc: Build the CLI
    cmds:
      - go build -o slack-cli .

  run:
    desc: Run the CLI
    cmds:
      - go run . {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  install:
    desc: Install to $GOPATH/bin
    cmds:
      - go install .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f slack-cli
